repos:
  - repo: local
    hooks:
      - id: ruff.check
        name: ruff.check
        entry: poetry run ruff check --fix
        language: system
        pass_filenames: true
        types:
          - python
      - id: ruff.format
        name: ruff.format
        entry: poetry run ruff format
        language: system
        pass_filenames: true
        types:
          - python
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        pass_filenames: true
        types:
          - python
