name: Dependabot merge
on:
  pull_request:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve patch updates
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.AUTO_MERGE_TOKEN}}
      - name: Approve development updates
        if: ${{steps.metadata.outputs.update-type != 'version-update:semver-patch' && steps.metadata.outputs.dependency-type == 'direct:development'}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.AUTO_MERGE_TOKEN}}
